### ISSUE TITLE
Error given when trying .get_feature(index)

### ISSUE THREAD

**Issue by cj2001** [karimbahgat/PyGeoj#3]
Hello.

Following your README looking at a lengthy geoJSON on my end, I get the following error when I run testfile.get_feature(3).  Am I doing something wrong?

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-33-18c728e533bc> in <module>()
----> 1 testfile.get_feature(3)

/usr/local/lib/python2.7/dist-packages/pygeoj.pyc in get_feature(self, index)
    495         - A Feature instance.
    496         """
--> 497         return self[oldindex]
    498 
    499     def replace_feature(self, oldindex, newfeature):

NameError: global name 'oldindex' is not defined

**Comment by karimbahgat** [comment]
You are not doing anything wrong. That was a bug on my end, I mistakenly told get_feature() to look for "oldindex" when it should have been "index". Fixed it, updated github repo, and uploaded patched version on pypi, so if you reinstall/update your pygeoj package it should now be fixed.
Note also that I changed to semantic versioning, so the new version is called 0.2.3.
