### ISSUE TITLE
GeoJSON saved doesn't validate on geoJSONlint?

### ISSUE THREAD

**Issue by mave007** [karimbahgat/PyGeoj#4]
So probably I have an issue understanding the geojson format, but when i try to create multiple points, and then i use [http://geojsonlint.com](http://geojsonlint.com/) to validate, I always find a message that says:
> GeoJSON features must have a type=feature property

So, Is it possible to add that type for each property?

**Comment by lalstef** [comment]
Hi @karimbahgat , @mave007 ,

The problem occurs when creating features 'directly', instead with the Feature class:
```
geojson = pygeoj.new()
geojson.add_feature(geometry=geometry, properties=properties)
geojson.save('data.geojson')
```
But is fine when you do:
```
feature = Feature(geometry=geometry, properties=properties)
geojson.add_feature(feature)
geojson.save('data.geojson')
```

**Comment by karimbahgat** [comment]
@lalstef @mave007 ,

Well spotted. Indeed, when using add_feature() directly I had forgot to add the type=Feature. Fixed in the most recent commit, so update your PyGeoj and see if works now. Also added a check on the type, so that running validate() on the feature or entire Geojfile object should pick up on this too now.

**Comment by fjansson** [comment]
I ran into the same issue using the version on pypi (pip install pygeoj). Any chance you could update the pypi package? Of course the work-around shown in the top post can be used until then.

**Comment by karimbahgat** [comment]
Looks like I had just forgotten to update PyPI with the most recent GitHub bugfixes. PyPI is now updated with version 0.2.5 where this is fixed.
