### ISSUE TITLE
Getting old version from PyPI

### ISSUE THREAD

**Issue by deeplook** [karimbahgat/PyGeoj#8]
When in `pip install pygeoj` from PyPI I get version 0.22 instead of 0.2.5, so I assume something must be wrong with the version as specified for distutils/setuptools, maybe?

```
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pygeoj

In [2]: pygeoj.__version__
Out[2]: '0.22'
```

Only if I `pip install pygeoj==0.2.5` I get the current version.

**Comment by deeplook** [comment]
For the same reason the `bbox` attribute didn't work as expected before, which made me implement my own in this snippet here: https://gist.github.com/deeplook/1758c1ad82f0e288eb78ab1cd5d697b4 But, hey, it was fun.

**Comment by karimbahgat** [comment]
Yes, I've had some issues keeping this up to date, but pypi is now caught up in a new stable version 1.0 which includes all the recent bugfixes and PRs.
